POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "fullstack fullstack front to back to databse to testing",
    "important": true,
    "userId": "637b60bf65a4f85a1a4843cc"
}