POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob3ZhcCIsImlkIjoiNjM3YmZlODA4ODMwMDM1YmQzZDdlY2I0IiwiaWF0IjoxNjY5MTA2ODU2LCJleHAiOjE2NjkxMTA0NTZ9.FBUWXjNYPb54EPJsOqOilBzzSLgXWR3WsP4QveyMY3A

{
    "title": "Lets visit zoo today",
    "auther": "Pandey mishra",
    "url": "www.zoo.com"
}