POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNob3ZhcCIsImlkIjoiNjM3YmZlODA4ODMwMDM1YmQzZDdlY2I0IiwiaWF0IjoxNjY5MTEwNjExLCJleHAiOjE2NjkxMTQyMTF9.1vwKaUcVljVA-LqHN_pFYcBaXnJzB_ldTfvJI_Vrzus

{
    "title": "Dark winter",
    "auther": "Pandey mishra",
    "url": "www.zoo.com"
}